---
language: ruby
bundler_args: --without development
script: 'bundle exec rake validate && SPEC_OPTS="--format documentation" bundle exec rake spec'
matrix:
  fast_finish: true
  include:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.5
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.5
      env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
    - rvm: 2.1.6
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
    - rvm: 2.4.1
      env: PUPPET_GEM_VERSION="~> 5.0"
    - rvm: 2.5.1
      env: PUPPET_GEM_VERSION="~> 6.0"
notifications:
  email: false
